### ISSUE TITLE
GinLog may take too long in a large project...

### ISSUE THREAD

**Issue by atusy** [lambdalisue/gin.vim#116]
For example, https://github.com/neovim/neovim

As far as I tried, `GinLog --oneline --graph` takes several seconds and is longer than `GinLog`.

In terminal, pagers does the good job.

Is there a possibility that `GinLog` (or maybe `GinBuffer`?) appends stdout to buffer asynchronously so that Vim is less blocked?

**Comment by lambdalisue** [comment]
Unfortunately, it cannot.

Unlike Gina, Gin is designed not to perform asynchronous buffer updates. So, for example, `GinLog | echo "Hello"` will execute `Hello` only after the `GinLog` buffer is fully processed. This decision is due to the fact that asynchronous updates like Gina's are not compatible with other native Vim features, leading to reduced usability and unexpected bugs, so we have no plans to change this fundamental design, at least at this stage.

**Comment by atusy** [comment]
I see! Thanks

For now, I limit the size eith -n
